#baseURL = 'https://www.bchainlab.it/'
baseURL = 'https://www.bchainlab.it'

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = true

[languages.en]
languageName = "EN"
weight = 2
contentDir = "content/en"


[languages.it]
languageName = "IT"
weight = 1
contentDir = "content/it"

description = "A new web3 company focused on blockchain technologies, NFT and privacy."

title = 'BChainLab'

publishDir = "docs"
staticDir = ['assets']


[params]
  copyright = "Copyright © 2023 Covenant Srls. P.IVA 14635081004. Via Flavia, 47 - 00187 Roma. Tutti i diritti riservati."
  description = "The New Web3 Software and Privacy Company"

